syntax enable

set background=dark
colorscheme solarized
:highlight normal ctermbg=234
"let g:solarized_contrast="high"
"let g:solarized_visibility="high"
"let g:solarized_termcolors=256

set nu
set shiftwidth=2
set smartindent
set backspace=indent,eol,start
set laststatus=2
set ignorecase
set smartcase
set cursorline
set expandtab
set tabstop=2
set splitright
set pastetoggle=<F5>
set mouse=a

" Disable comment continuation on new line
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Remove trailing spaces
autocmd BufWritePre * %s/\s\+$//e

" Tab to spaces
"autocmd BufWritePre * retab

" Do not destroy Makefiles
autocmd FileType make setlocal noexpandtab

" Disable markdown auto-folding
let g:vim_markdown_folding_disabled=1

" Disable concealing of double quotes in json
" let g:vim_json_syntax_conceal=0

" shortcuts
noremap <C-n> :NERDTreeToggle<CR>
noremap <F6> :set syntax=yaml<CR>
inoremap jj <Esc>
vnoremap jj <Esc>
inoremap jk <Esc>:w<CR>
inoremap jl <Esc>:wq<CR>

" Open NERDTree on startup, when no file has been specified
autocmd VimEnter * if !argc() | NERDTree | endif

" re-open file where we left (make sure ~/.viminfo is owned by user)
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
"    \| exe "normal! g'\"" | endif
"endif

noremap <C-l> :BufExplorer<CR>
noremap <C-h> :GoTest<CR>
noremap <C-j> :GoRun<CR>
noremap <C-i> :GoImports<CR>

filetype plugin on
filetype indent on

" By default syntax-highlighting for Functions, Methods and Structs is disabled.
" Let's enable them!
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1

"set hlsearch
"set incsearch
