ssh-add --apple-load-keychain

eval "$(/opt/homebrew/bin/brew shellenv)"

source ~/.aliases.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export STARSHIP_CONFIG=~/.starship.toml
eval "$(starship init zsh)"

export PATH=$PATH:~/go/bin

export GOPRIVATE=slack-github.com
export LAPTOP_DEV=true

