# Allows things to play nice together
autoload -U compinit compdef
compinit

# gcloud
source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc
source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc

# custom
source ~/code/github.com/diist/dotfiles/cfg/zsh/git.zsh
source ~/code/github.com/diist/dotfiles/cfg/zsh/exports.zsh
source ~/code/github.com/diist/dotfiles/cfg/zsh/aliases.zsh
source ~/code/github.com/diist/dotfiles/cfg/zsh/functions.zsh
source ~/code/github.com/diist/dotfiles/cfg/zsh/history.zsh
source ~/code/github.com/diist/dotfiles/cfg/zsh/antigen.zsh

# Update / change plugins
antigen bundles <<EOBUNDLES
  fzf
  command-not-found
  docker
  docker-compose
  colored-man-pages
  jonmosco/kube-ps1
  olivierverdier/zsh-git-prompt
  zsh-users/zsh-completions
EOBUNDLES

antigen theme robbyrussell
antigen apply

# ps1
setopt prompt_subst
source ~/code/github.com/diist/dotfiles/cfg/zsh/ps1.zsh
