# gcloud
source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc
source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc

# custom
source ~/code/github.com/diist/dotfiles/cfg/zsh/git.zsh
source ~/code/github.com/diist/dotfiles/cfg/zsh/exports.zsh
source ~/code/github.com/diist/dotfiles/cfg/zsh/aliases.zsh
source ~/code/github.com/diist/dotfiles/cfg/zsh/functions.zsh
source ~/code/github.com/diist/dotfiles/cfg/zsh/history.zsh
source ~/code/github.com/diist/dotfiles/cfg/zsh/zgen.zsh

if ! zgen saved; then
  zgen oh-my-zsh

  zgen oh-my-zsh plugins/fzf
  zgen oh-my-zsh plugins/command-not-found
  zgen oh-my-zsh plugins/docker
  zgen oh-my-zsh plugins/docker-compose
  zgen oh-my-zsh plugins/colored-man-pages

  zgen load jonmosco/kube-ps1
  zgen load olivierverdier/zsh-git-prompt
  zgen load zsh-users/zsh-completions

  zgen oh-my-zsh themes/robbyrussell

  zgen save
fi

# ps1
setopt prompt_subst
source ~/code/github.com/diist/dotfiles/cfg/zsh/ps1.zsh
